FROM nginx:1.15

RUN mkdir -p /damafactory/app

RUN find /damafactory/app -type d -exec chmod 755 {} \;
RUN find /damafactory/app -type f -exec chmod 644 {} \;

VOLUME /usr/share/nginx/html
VOLUME /etc/nginx
VOLUME /damafactory/app

EXPOSE 80
EXPOSE 443